services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: false

  WechatMiniProgramInsuranceFreightBundle\Controller\:
    resource: '../../Controller/'
  WechatMiniProgramInsuranceFreightBundle\Repository\:
    resource: '../../Repository/'
  WechatMiniProgramInsuranceFreightBundle\Service\:
    resource: '../../Service/'
    public: true
  WechatMiniProgramInsuranceFreightBundle\Command\:
    resource: '../../Command/'
  WechatMiniProgramInsuranceFreightBundle\EventSubscriber\:
    resource: '../../EventSubscriber/'
    public: true
